import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Playfair_Display, Inter } from "next/font/google"; // Importando as novas fontes
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configuração da fonte principal (Tan Garland)
const tanGarland = Playfair_Display({
  variable: "--font-tan-garland",
  subsets: ["latin"],
  display: "swap",
});

// Configuração da fonte secundária (Clear Sans)
const clearSans = Inter({
  variable: "--font-clear-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Livi Skov Ministries", // Título atualizado aqui
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tanGarland.variable} ${clearSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}